name: Test

on:
  workflow_dispatch:

jobs:
  # Contains a single job called "build"
  build:
    runs-on: self-hosted
    steps:
      # Checks out repository under $GITHUB_WORKSPACE, so job can access it
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

