name: Example Workflow
on:
  push:
    branches: [ developer ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: approvers
      uses: trstringer/manual-approval@v1
      with:
        secret: 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
        approvers: kagupatipavan