name: Example Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    environment: final
    steps:
     - name: copy dev docker file to dockerfile
       run: cp dev.Dockerfile dockerfile
     - name: show copied dockerfile
       run: cat dockerfile
