name: Example Workflow
on:
  push:
    branches: [ developer ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Building..."
          echo "::set-output name=success::true"
      - name: Test
        run: |
          echo "Running tests..."
          echo "::set-output name=success::true"
      - name: Deploy
        if: ${{ 'true' == 'true' }}
        steps:
          - name: Deploy to Staging
            run: echo "Deploying to staging..."
          - name: Deploy to Production
            run: echo "Deploying to production..."
