name: Example Workflow
on:
  push:
    branches: [ developer ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Building..."
          echo "::set-output name=success::true"
  prodbuild:
    runs-on: self-hosted
    if: ${{ 'name' == 'name'}}
    steps:
      - name: prod started
        run: echo "prd"
  devBuild:
    runs-on: self-hosted
    if: ${{ 'name' == 'dev'}}
    steps:
    - name: pavan king
      run: echo "herooo"
