name: Example Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: final
    steps:
    - name: build
      run: echo "$ls"
    - name: build app
      run: docker build -t pavandocker dev.Dockerfile
   
