name: Example Workflow
on:
  push:
    branches: [ developer ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        id: tests
        run: |
          echo "Running tests..."
          echo "::set-output name=success::true"
        if: ${{ 'true' == 'true' }}
      - name: pavan new
        run: |
          echo "Deploying..."
          echo "Cleaning up..."
      - name: hehehe
        run: echo "Heating..."