name: Example Workflow
on:
  push:
    branches: [ developer ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        id: tests
        run: |
          echo "Running tests..."
          echo "::set-output name=success::true"
      - name: Deploy
        if: ${{ steps.tests.outputs.success == 'true' }}
        run: |
          echo "Deploying..."
          echo "Cleaning up..."
