name: Example Workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: final
    steps:
    - name: approvers
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{secrets.TOKEN_SECRET}}
        approvers: kagupatipavan